apps/customers/urls.py
from django.urls import path

from . import views

app_name = 'customers'
urlpatterns = [
    path('', views.CustomerFilterView.as_view(), name='customer_search'),
    path('<pk>/detail', views.CustomerDetailView.as_view(), name='customer_detail'),
    path('<pk>/edit', views.CustomerUpdateView.as_view(), name='customer_update'),
    path('new', views.CustomerCreateView.as_view(), name='customer_create'),
    path('<pk>/delete', views.CustomerDeleteView.as_view(), name='customer_delete'),
]

django_filter_datatables/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from . import views

handler500 = views.handler500

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('customers/', include('apps.customers.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:

    urlpatterns += [
        path('403/', TemplateView.as_view(template_name='403.html')),
        path('404/', TemplateView.as_view(template_name='404.html')),
        path('500/', TemplateView.as_view(template_name='500.html')),
        path('503/', TemplateView.as_view(template_name='503.html')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/customers/models.py
from django.db import models
from django.shortcuts import reverse


class Customer(models.Model):
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    state = models.CharField(max_length=255, blank=True)
    zip = models.CharField(max_length=10, blank=True)
    phone = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return f'{self.last_name} {self.first_name}'

    def get_absolute_url(self):
        return reverse('customers:customer_detail', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('customers:customer_delete', kwargs={'pk': self.pk})

apps/utils/models.py
from django.db import models

# Create your models here.

apps/customers/forms.py
from django import forms

from . import models


class CustomerForm(forms.ModelForm):
    class Meta:
        model = models.Customer
        fields = ('first_name', 'last_name', 'city', 'state', 'zip', 'phone', )

apps/customers/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.views import View
from django.views.generic import UpdateView, CreateView, DetailView

from apps.utils.views import FilterView
from . import forms, filters, models, helpers


class CustomerFilterView(FilterView):
    sorting = {0: ['last_name'], 1: ['first_name']}
    values = ('pk',)
    object_class = models.Customer
    filter_class = filters.CustomerFilter
    template_name = 'customers/customer_filter.html'

    @staticmethod
    def result_function(qs):
        result = []

        for b in qs:
            object = models.Customer.objects.get(pk=b['pk'])
            col = {"last_name": helpers.format_link(object.get_absolute_url(), object.last_name),
                   "first_name": object.first_name}
            result.append(col)
        return result


class CustomerDetailView(DetailView):
    template_name = 'customers/customer_detail.html'
    queryset = models.Customer.objects.all()


class CustomerUpdateView(UpdateView):
    template_name = 'customers/customer_update.html'
    queryset = models.Customer.objects.all()
    form_class = forms.CustomerForm


class CustomerCreateView(CreateView):
    template_name = 'customers/customer_update.html'
    model = models.Customer
    form_class = forms.CustomerForm


class CustomerDeleteView(View):
    object_class = models.Customer

    def get(self, request, pk):
        object = get_object_or_404(self.object_class, pk=pk)
        edit_url = reverse('customers:customer_update', kwargs={'pk': pk})
        return render(
            request,
            'generic_confirm_delete.html',
            {'object': object, 'title': 'Customer', 'cancel_url': edit_url},
        )

    def post(self, request, pk):
        object = get_object_or_404(self.object_class, pk=pk)
        object.delete()
        return redirect('customers:customer_search')

apps/utils/views.py
import logging
from django.http import QueryDict
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View

logger = logging.getLogger('util_views')


class FilterView(View):
    # these variables needs to be defined in child class
    sorting = None
    values = None
    object_class = None
    filter_class = None
    template_name = None

    @staticmethod
    def result_function(qs):
        raise NotImplementedError(
            'AjaxSearchView class requires .result_function() to be implemented'
        )

    @staticmethod
    def json_sort_helper(columns, sorting):
        order_list = []
        for column in columns:
            if column['name'] in sorting.keys():
                for item in sorting[column['name']]:
                    # reverse order
                    if '-' in item:
                        if column['direction'] == 'asc':
                            order_list.append(item)
                        else:
                            # remove '-'
                            order_list.append(item.replace('-', ''))

                    # normal order
                    else:
                        if column['direction'] == 'asc':
                            order_list.append(item)
                        else:
                            order_list.append("-{}".format(item))
        return order_list

    def get(self, request):
        return render(request, self.template_name, {'filter': self.filter_class()})

    def post(self, request):
        columns = []

        # could be sorting by multiple columns
        for i in range(len(self.sorting)):

            direction = request.POST.get("order[{}][dir]".format(i), None)
            if direction:
                column = int(request.POST.get("order[{}][column]".format(i), '0'))
                columns.append({'name': column, 'direction': direction})

        order_list = self.json_sort_helper(columns, self.sorting)

        draw = int(request.POST.get('draw', '0'))
        start = int(request.POST.get('start', '0'))
        length = int(request.POST.get('length', '0'))
        values = QueryDict(request.body.decode('utf-8').replace('%5B%5D', ''))

        f = (
            self.filter_class(values, queryset=self.object_class.objects.all())
                .qs.values(*self.values)
                .order_by(*order_list)
        )
        count = len(f)

        # -1 is the all option
        if length == -1:
            results = f
        else:
            results = f[start: length + start]

        r = {
            "draw": draw,
            "recordsTotal": count,
            "recordsFiltered": count,
            "data": self.result_function(results),
        }
        return JsonResponse(r)

django_filter_datatables/views.py
from django.http import HttpResponseServerError
from django.shortcuts import render
from django.template import loader
from django.views import View


class Index(View):
    def get(self, request):
        return render(request, 'index.html')


def handler500(request):
    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render({'request': request}))

apps/customers/templates/customers/customer_detail.html
{% extends 'base.html' %}
{% load bootstrap3 static_tags %}
{% block title %}Customer{% endblock title %}
{% block page_content %}

    <div class="panel">
        <div class="panel-body">
            {% csrf_token %}
            <fieldset class="col-sm-6">
                {% static_field object "first_name" %}
                {% static_field object "last_name" %}
                {% static_field object "city" %}
                {% static_field object "state" %}
                {% static_field object "zip" %}
                {% static_field object "phone" %}
            </fieldset>
        </div>
    </div>

    {% if perms.update_customer %}
        <div class="col-xs-5 page-header-buttons">
            <a href="{% url 'customers:customer_update' object.id %}" class="btn btn-default btn-purple">
                <span class="fa fa-edit"></span> Edit</a>
        </div>
    {% endif %}

{% endblock page_content %}

apps/customers/templates/customers/customer_filter.html
{% extends 'base.html' %}

{% load bootstrap3 %}
{% load static %}

{% block title %}Customer Search{% endblock title %}
{% block js_top %}
    {{ block.super }}

    <script type="text/javascript">

        $(document).ready(function () {
            //sets focus to first input
            $('input[type=text],select').filter(':visible:first').focus();
        });

        //Bind keypress event
        $(document).keypress(function (event) {
            var keycode = (event.keyCode ? event.keyCode : event.which);
            if (keycode == '13') {
                search();
            }
        });

        function search() {
            $('div#collapseOne').removeClass("show" );
            $('div#collapseOne').addClass("collapse" );
            $('div#collapseTwo').removeClass("collapse" );
            $('div#collapseTwo').addClass("show" );

            var $searchCriteria = searchCriteriaCollection(true);
            $('#results').DataTable({
                "searching": false,
                "paging": true,
                "pageLength": 25,
                "serverSide": true,
                "order": [[0, "asc"]],
                "destroy": true,
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "ajax": {
                    "url": "{% url 'customers:customer_search'  %}",
                    "data": $searchCriteria,
                    "type": "POST"
                },
                columns: [
                    {data: 'last_name', "title": 'Last Name'},
                    {data: 'first_name', "title": 'First Name'},
                ],

            });
        }
    </script>

{% endblock js_top %}

{% block page_header_title %}
    <div class="col-xs-7 page-header-content">
        <i class="psi-calendar-4"></i>
        Customer Search
    </div>

    {% if perms.create_event %}
        <div class="col-xs-5 page-header-buttons">
            <a href="{% url 'customers:customer_create' %}" class="btn btn-default btn-purple">
                <span class="fa fa-plus"></span> Add New</a>
        </div>
    {% endif %}

{% endblock page_header_title %}

{% block page_content %}
    <div class="row">
        <div class="col-md-12">
            <div class="agent-quick-search">
                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Search Criteria</a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse show">
                            <div class="panel-body">
                                {% csrf_token %}

                                <fieldset class="col-sm-6">
                                    {% bootstrap_field filter.form.first_name %}
                                    {% bootstrap_field filter.form.last_name %}
                                    {% bootstrap_field filter.form.city %}
                                    {% bootstrap_field filter.form.state %}
                                    {% bootstrap_field filter.form.zip %}
                                    {% bootstrap_field filter.form.phone %}
                                </fieldset>

                                <fieldset class="col-sm-6">
                                    {% buttons %}
                                        <label class="control-label">&nbsp;</label>
                                        <button
                                                class="btn btn-primary btn-full-width"
                                                name="search"
                                                onclick="search()">
                                            Search
                                        </button>
                                    {% endbuttons %}
                                </fieldset>

                            </div>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Search Results</a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse">
                            <div class="panel-body">
                                <div class="col-sm-12">
                                    <table id="results" class="table table-striped table-bordered">
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

apps/customers/templates/customers/customer_update.html
{% extends 'base.html' %}
{% block title %}Customer{% endblock title %}
{% load bootstrap3 %}

{% block page_header_title %}
    <div class="col-xs-7 page-header-content">
        <i class="psi-calendar-4"></i>
        {% if form.instance.id %}
            {{ form.instance.id }}
        {% else %}
            New Customer
        {% endif %}
    </div>
{% endblock page_header_title %}

{% block js_top %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            $('#id_date').datetimepicker({format: 'L'});
        });
    </script>
{% endblock js_top %}

{% block page_content %}

    <div class="panel col-sm-10 col-sm-offset-1">
        <div class="panel-heading">
            <h3 class="panel-title">Customer</h3>
        </div>
        <form action="" method="post" class="form">
            <div class="panel-body">
                {% csrf_token %}
                <fieldset class="col-sm-6">
                    {% bootstrap_field form.first_name %}
                    {% bootstrap_field form.last_name %}
                    {% bootstrap_field form.city %}
                    {% bootstrap_field form.state %}
                    {% bootstrap_field form.zip %}
                    {% bootstrap_field form.phone %}
                </fieldset>
            </div>

            <div class="panel-footer text-right">
                {% bootstrap_button "Save" button_type="submit" name="save" button_class="btn btn-success" %}

                {% if form.instance.pk %}
                    <a href="{{ form.instance.get_absolute_url }}" class="btn btn-default btn-warning"> Cancel </a>
                    <a href="{{ form.instance.get_delete_url }}" class="btn btn-default btn-danger"> Delete </a>
                {% else %}
                    <a href="{% url 'customers:customer_search' %}" class="btn btn-default btn-warning"> Cancel </a>
                {% endif %}
            </div>

        </form>
    </div>
{% endblock page_content %}

django_filter_datatables/templates/503.html
{% extends 'base.html' %}

{% block page_header_title %}
    <div class="col-xs-7 page-header-content">
        503
    </div>
{% endblock page_header_title %}

{% block page_content %}
    <div class="panel col-sm-10 col-sm-offset-1">
        <div class="panel-heading">
            <p>The site is currently down for maintenance.  Please try back later. </p>
        </div>
    </div>
{% endblock page_content %}

django_filter_datatables/templates/base.html
{% load static %}
{% load active_link_tags %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Django Filter Datatables - {% block title %}{% endblock title %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/vendor/fontawesome-free/css/all.min.css' %}"
          rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/css/sb-admin-2.min.css' %}" rel="stylesheet"
          type="text/css">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->

        <a class="sidebar-brand d-flex align-items-center justify-content-center"
           href="{% url 'customers:customer_search' %}">
            <i class="fas fa-portrait fa-4x"></i>
            <div class="sidebar-brand-text mx-3">Customers</div>
        </a>


        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->

        <!-- Nav Item - Charts -->

        <li class="nav-item {% active_link 'admin:index' %}">
            <a class="nav-link" href="{% url 'admin:index' %}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Admin Center</span></a>
        </li>


        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">


        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">username</span>
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
{#                            <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i#}
{#                                    class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Logout</a>#}
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Content Row -->
                <!-- Error Messages -->
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                {% block page_content %}{% endblock page_content %}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Django Filter Datatables</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js' %}"></script>

{# more resources #}

{% block css %}
    <link href="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/vendor/datatables/dataTables.bootstrap4.min.css' %}"
          rel="stylesheet">
{% endblock css %}

{% block js_top %}
    <script src="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'theme/startbootstrap-sb-admin-2-gh-pages/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'js/util.js' %}"></script>
{% endblock js_top %}

</body>

</html>

django_filter_datatables/templates/generic_confirm_delete.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}{{ title }} - {{ object }}{% endblock %}

{% block page_header_title %}
{% endblock page_header_title %}

{% block page_content %}
    {#    <div class="row">#}
    <div class="panel col-sm-8 col-sm-offset-2">
        <div class="panel-heading">
            <h3 class="panel-title">Confirm Deletion</h3>
        </div>
        <form action="" method="post" role="form">
            <div class="panel-body">
                {% csrf_token %}
                <p>Are you sure you want to <span class="text-bold">delete</span> the record
                    for {{ object }}?</p>
            </div>
            <div class="panel-footer text-right">

                {% bootstrap_button "Cancel" button_type="link" name="cancel" href=cancel_url button_class="btn btn-warning" %}

                {% bootstrap_button "Delete" button_type="link" name="delete" button_class="btn btn-danger" %}
            </div>
        </form>
    </div>
{% endblock page_content %}

django_filter_datatables/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% load static_tags %}

{% block title %}
    Welcome
{% endblock title %}

{% block page_content %}
    <h1>Welcome</h1>
{% endblock page_content %}


{% block js_bottom %}
    {{ block.super }} %}
{% endblock js_bottom %}